singleQuote: true

importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - '^react($|/)'
  - '^next($|/)'
  - '<THIRD_PARTY_MODULES>'

  - '<SEPARATOR>'

  - '^@/i18n/(.*)$'
  - '^@/lib/(.*)$'
  - '^@/components/ui/(.*)$'
  - '^@/components/(.*)$'
  - '^@/app/(.*)$'
  - '^@/(.*)$'
  - '^[./]'
  - '^.+\\.css$'

plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-tailwindcss'
